version: '2.3'
services:
    docker-head:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "10385:22"
